# Generated by Django 6.0.4 on 2026-04-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0003_eventoutbox_last_error_eventoutbox_next_attempt_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantuser',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='merchantuser',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('OPERATOR', 'Operator'), ('VIEWER', 'Viewer')], default='OPERATOR', max_length=20),
        ),
    ]
