from django.urls import path

from .views import (
    AccountChangePasswordView,
    AccountProfileView,
    AdminHomeView,
    ApiKeyView,
    AuthLoginView,
    AuthLogoutView,
    AuthMeView,
    AuthRefreshView,
    AuthRegisterView,
    MerchantBankAccountsView,
    MerchantBalanceView,
    MerchantLedgerView,
    MerchantListView,
    MerchantRiskProfileView,
    MerchantWebhookDeliveriesView,
    MerchantPayoutsView,
    OperatorHomeView,
    PayoutCreateView,
    PayoutDetailView,
    WebhookEndpointView,
)

urlpatterns = [
    path('merchants/', MerchantListView.as_view()),
    path('auth/register/', AuthRegisterView.as_view()),
    path('auth/login/', AuthLoginView.as_view()),
    path('auth/refresh/', AuthRefreshView.as_view()),
    path('auth/logout/', AuthLogoutView.as_view()),
    path('auth/me/', AuthMeView.as_view()),
    path('account/profile/', AccountProfileView.as_view()),
    path('account/change-password/', AccountChangePasswordView.as_view()),
    path('operator/home/', OperatorHomeView.as_view()),
    path('admin/home/', AdminHomeView.as_view()),
    path('merchants/<int:merchant_id>/balance/', MerchantBalanceView.as_view()),
    path('merchants/<int:merchant_id>/bank-accounts/', MerchantBankAccountsView.as_view()),
    path('merchants/<int:merchant_id>/ledger/', MerchantLedgerView.as_view()),
    path('merchants/<int:merchant_id>/payouts/', MerchantPayoutsView.as_view()),
    path('merchants/<int:merchant_id>/risk-profile/', MerchantRiskProfileView.as_view()),
    path(
        'merchants/<int:merchant_id>/webhook-deliveries/',
        MerchantWebhookDeliveriesView.as_view(),
    ),
    path('payouts/', PayoutCreateView.as_view()),
    path('payouts/<int:payout_id>/', PayoutDetailView.as_view()),
    path('api-keys/', ApiKeyView.as_view()),
    path('webhook-endpoints/', WebhookEndpointView.as_view()),
]
